### ISSUE TITLE
Unable to connect to COS bucket , Getting 403 Forbidden error 

### ISSUE THREAD

**Issue by PrashanthBoraiah** [ibm-messaging/kafka-connect-ibmcos-sink#12]
Using kafka-connect-ibmcos-sink. when I tried to connect to COS , am getting 403 Forbidden error messages in the  console.log of connector . 

We deployed "kafka-connect-ibmcos-sink" in  IBM softlayer  box.  and tried to run it in distributed mode .

We  have provided apikey and crn of the service credentials and provided access permission to our bucket .  When tried using curl commands we are able to connect with same credentials and list the buckets . But through connector we are facing this issue.

console log file:

[2020-12-08 03:32:01,510] INFO COSSinkConnectorConfig values:
        cos.api.key = [hidden]
        cos.bucket.location = us-east
        cos.bucket.name = 
        cos.bucket.resiliency = regional
        cos.endpoint.visibility = private
        cos.endpoints.url = https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints
        cos.object.deadline.seconds = -1
        cos.object.interval.seconds = 36000000
        cos.object.record.delimiter.nl = false
        cos.object.records = 5
        cos.service.crn = somestring
 (com.ibm.eventstreams.connect.cossink.COSSinkConnectorConfig:347)
[2020-12-08 03:32:01,511] INFO [Worker clientId=connect-1, groupId=woo-hdfs-connector-group-devint] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1125)
403
Forbidden
sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@fa5b4173
[2020-12-08 03:32:01,540] ERROR WorkerSinkTask{id=cos-sink-srcplan-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
com.ibm.cos.ClientFactoryException: java.io.IOException: Unable to retrieve endpoint information from: https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints
        at com.ibm.cos.ClientFactoryImpl.newClient(ClientFactoryImpl.java:42)
        at com.ibm.eventstreams.connect.cossink.COSSinkTask.start(COSSinkTask.java:105)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:301)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
        at java.util.concurrent.FutureTask.run(FutureTask.java:277)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:820)
Caused by: java.io.IOException: Unable to retrieve endpoint information from: https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints
        at com.ibm.cos.endpoints.Endpoints.fetch(Endpoints.java:81)
        at com.ibm.cos.ClientFactoryImpl.newClient(ClientFactoryImpl.java:39)
        ... 10 more
[2020-12-08 03:32:01,540] ERROR WorkerSinkTask{id=cos-sink-srcplan-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:180)

cos-sink.json file 

 "name": "cos-sink-ol",
    "config":{
        "connector.class": "com.ibm.eventstreams.connect.cossink.COSSinkConnector",
        "tasks.max": "1",
        "topics": "xxxxxxxxxxxxxxxxxxxxxxxxx",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "value.converter": "org.apache.kafka.connect.storage.StringConverter",
        "cos.api.key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "cos.bucket.location": "us-east",
        "cos.bucket.name": "cos-connector-bucket-dev",
        "cos.bucket.resiliency": "regional",
        "cos.endpoint.visibility": "private",
        "cos.object.interval.seconds": "1000",
        "cos.object.records": "2",
        "cos.service.crn": "some_value",
        "cos.endpoints.url":"https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints",
        "cos.object.parquet.schema": "{\xxxxxxxxxxxxxxxxxxx\"}]}"

**Comment by VidyasagarMSC** [comment]
👍 seeing the same issue with Kubernetes on VPC gen 2

**Comment by l2fprod** [comment]
Same issue `Unable to retrieve endpoint information from: https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints`

And found the reason why, the code needs to set the `User-Agent` property in https://github.com/ibm-messaging/kafka-connect-ibmcos-sink/blob/aa19d54cdd7161dc1ccea7b7226b17059c7732d3/src/main/java/com/ibm/cos/endpoints/Endpoints.java#L71

To confirm, I added 

```java
    public static void main(String[] args) throws Exception {
        Endpoints ep = fetch(args[0]);
        System.out.println(ep.crossRegion());
    }
```

Testing with Java 1.8: 

```
java -cp build/libs/kafka-connect-ibmcos-sink-1.0.0-all.jar com.ibm.cos.endpoints.Endpoints https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints
Exception in thread "main" java.io.IOException: Unable to retrieve endpoint information from: 403 https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints
	at com.ibm.cos.endpoints.Endpoints.fetch(Endpoints.java:84)
	at com.ibm.cos.endpoints.Endpoints.main(Endpoints.java:70)
```

And when passing a user-agent, it works:

```
java -Dhttp.agent=blah -cp build/libs/kafka-connect-ibmcos-sink-1.0.0-all.jar com.ibm.cos.endpoints.Endpoints https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints
{eu=public=s3.eu.cloud-object-storage.appdomain.cloud, private=s3.private.eu.cloud-object-storage.appdomain.cloud, us=public=s3.us.cloud-object-storage.appdomain.cloud, private=s3.private.us.cloud-object-storage.appdomain.cloud, ap=public=s3.ap.cloud-object-storage.appdomain.cloud, private=s3.private.ap.cloud-object-storage.appdomain.cloud}
```

so a change like:

```java
    public static Endpoints fetch(String endpointsURL) throws IOException {
        final URL url = new URL(endpointsURL);
        final HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setRequestMethod("GET");
        connection.setInstanceFollowRedirects(true);
        connection.setRequestProperty("User-Agent", "kafka-connect-ibmcos-sink"); // COS expects a user agent to be set
        connection.setReadTimeout(15 * 1000);
```

should solve this problem

**Comment by mimaison** [comment]
Thanks @l2fprod for the investigation. Can you raise a Pull Request with the fix?

**Comment by VidyasagarMSC** [comment]
@mimaison 


@l2fprod has already opened a pull request https://github.com/ibm-messaging/kafka-connect-ibmcos-sink/pull/14. Can you verify and merge at the earliest.
